/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedDashboardlayoutImport } from './routes/_protected/_dashboardlayout'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as ProtectedDashboardlayoutTransactionsImport } from './routes/_protected/_dashboardlayout.transactions'
import { Route as ProtectedDashboardlayoutSettingsImport } from './routes/_protected/_dashboardlayout.settings'
import { Route as ProtectedDashboardlayoutDashboardImport } from './routes/_protected/_dashboardlayout.dashboard'
import { Route as ProtectedDashboardlayoutBudgetImport } from './routes/_protected/_dashboardlayout.budget'
import { Route as ProtectedDashboardlayoutAnalyticsImport } from './routes/_protected/_dashboardlayout.analytics'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProtectedDashboardlayoutRoute = ProtectedDashboardlayoutImport.update({
  id: '/_protected/_dashboardlayout',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardlayoutTransactionsRoute =
  ProtectedDashboardlayoutTransactionsImport.update({
    path: '/transactions',
    getParentRoute: () => ProtectedDashboardlayoutRoute,
  } as any)

const ProtectedDashboardlayoutSettingsRoute =
  ProtectedDashboardlayoutSettingsImport.update({
    path: '/settings',
    getParentRoute: () => ProtectedDashboardlayoutRoute,
  } as any)

const ProtectedDashboardlayoutDashboardRoute =
  ProtectedDashboardlayoutDashboardImport.update({
    path: '/dashboard',
    getParentRoute: () => ProtectedDashboardlayoutRoute,
  } as any)

const ProtectedDashboardlayoutBudgetRoute =
  ProtectedDashboardlayoutBudgetImport.update({
    path: '/budget',
    getParentRoute: () => ProtectedDashboardlayoutRoute,
  } as any)

const ProtectedDashboardlayoutAnalyticsRoute =
  ProtectedDashboardlayoutAnalyticsImport.update({
    path: '/analytics',
    getParentRoute: () => ProtectedDashboardlayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_dashboardlayout': {
      preLoaderRoute: typeof ProtectedDashboardlayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_dashboardlayout/analytics': {
      preLoaderRoute: typeof ProtectedDashboardlayoutAnalyticsImport
      parentRoute: typeof ProtectedDashboardlayoutImport
    }
    '/_protected/_dashboardlayout/budget': {
      preLoaderRoute: typeof ProtectedDashboardlayoutBudgetImport
      parentRoute: typeof ProtectedDashboardlayoutImport
    }
    '/_protected/_dashboardlayout/dashboard': {
      preLoaderRoute: typeof ProtectedDashboardlayoutDashboardImport
      parentRoute: typeof ProtectedDashboardlayoutImport
    }
    '/_protected/_dashboardlayout/settings': {
      preLoaderRoute: typeof ProtectedDashboardlayoutSettingsImport
      parentRoute: typeof ProtectedDashboardlayoutImport
    }
    '/_protected/_dashboardlayout/transactions': {
      preLoaderRoute: typeof ProtectedDashboardlayoutTransactionsImport
      parentRoute: typeof ProtectedDashboardlayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  authSignInRoute,
  authSignUpRoute,
  ProtectedDashboardlayoutRoute.addChildren([
    ProtectedDashboardlayoutAnalyticsRoute,
    ProtectedDashboardlayoutBudgetRoute,
    ProtectedDashboardlayoutDashboardRoute,
    ProtectedDashboardlayoutSettingsRoute,
    ProtectedDashboardlayoutTransactionsRoute,
  ]),
])

/* prettier-ignore-end */
